/**
 * Async feature label loader — 20K SAE features from static JSON.
 * O(1) lookup by (block, featureId). Generated by scripts/transform_labels_for_frontend.py
 */

import type { BlockCode } from '../types/sae';

export interface FeatureEntry {
  id: number;
  label: string;
  category: string;
  confidence: 'high' | 'medium' | 'low';
  meanActivation: number;
}

type FeatureIndex = Record<BlockCode, Map<number, FeatureEntry>>;
type FeatureArrays = Record<BlockCode, FeatureEntry[]>;

const BLOCKS: BlockCode[] = ['down.2.1', 'mid.0', 'up.0.0', 'up.0.1'];

let _arrays: FeatureArrays | null = null;
let _index: FeatureIndex | null = null;
let _loadPromise: Promise<void> | null = null;

export async function loadFeatures(): Promise<void> {
  if (_arrays) return;
  if (_loadPromise) return _loadPromise;

  _loadPromise = (async () => {
    const arrays: Partial<FeatureArrays> = {};
    const index: Partial<FeatureIndex> = {};

    await Promise.all(
      BLOCKS.map(async (block) => {
        const resp = await fetch(`/data/features/${block}.json`);
        const entries: FeatureEntry[] = await resp.json();
        arrays[block] = entries;

        const map = new Map<number, FeatureEntry>();
        for (const e of entries) map.set(e.id, e);
        index[block] = map;
      })
    );

    _arrays = arrays as FeatureArrays;
    _index = index as FeatureIndex;
  })();

  return _loadPromise;
}

export function getBlockFeatures(block: BlockCode): FeatureEntry[] {
  return _arrays?.[block] ?? [];
}

export function getFeature(block: BlockCode, id: number): FeatureEntry | undefined {
  return _index?.[block]?.get(id);
}

export function featuresLoaded(): boolean {
  return _arrays !== null;
}
