/**
 * Async feature label loader — SAE feature labels from static JSON, keyed by
 * slot name. O(1) lookup by (slot, featureId).
 *
 * The slot list comes from the capability manifest at bootstrap. A slot
 * without a published label file (mock backend, future backends) resolves to
 * an empty list — FeaturePicker then degrades to its numeric ID spinner.
 * Label files are generated by scripts/transform_labels_for_frontend.py.
 */

export interface FeatureEntry {
  id: number;
  label: string;
  category: string;
  confidence: 'high' | 'medium' | 'low';
  meanActivation: number;
}

let _arrays: Record<string, FeatureEntry[]> = {};
let _index: Record<string, Map<number, FeatureEntry>> = {};
let _loaded = false;
let _loadPromise: Promise<void> | null = null;

export async function loadFeatures(slotNames: string[]): Promise<void> {
  if (_loaded) return;
  if (_loadPromise) return _loadPromise;

  _loadPromise = (async () => {
    const arrays: Record<string, FeatureEntry[]> = {};
    const index: Record<string, Map<number, FeatureEntry>> = {};

    await Promise.all(
      slotNames.map(async (slot) => {
        try {
          const resp = await fetch(`/data/features/${encodeURIComponent(slot)}.json`);
          arrays[slot] = resp.ok ? ((await resp.json()) as FeatureEntry[]) : [];
        } catch {
          arrays[slot] = [];
        }
        index[slot] = new Map(arrays[slot].map((e) => [e.id, e]));
      }),
    );

    _arrays = arrays;
    _index = index;
    _loaded = true;
  })();

  return _loadPromise;
}

export function getSlotFeatures(slot: string): FeatureEntry[] {
  return _arrays[slot] ?? [];
}

export function getFeature(slot: string, id: number): FeatureEntry | undefined {
  return _index[slot]?.get(id);
}

export function featuresLoaded(): boolean {
  return _loaded;
}
